
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '79A1E6908A9DEB1F54D04383C856FE8A'
    
_lr_action_items = {'COLUMN':([0,],[2,]),'-':([4,7,],[6,8,]),',':([9,12,15,16,18,20,22,],[10,14,-5,17,19,21,23,]),'.':([11,],[13,]),'INTEGER':([0,6,8,10,13,14,17,19,21,23,],[4,7,9,11,15,11,11,11,22,11,]),'$end':([1,2,3,5,15,24,],[-1,-3,0,-2,-5,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'column':([0,],[1,]),'start':([0,],[3,]),'float':([10,14,17,19,23,],[12,16,18,20,24,]),'data':([0,],[5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> column','start',1,'p_start','PlyMpstat.py',39),
  ('start -> data','start',1,'p_start','PlyMpstat.py',40),
  ('column -> COLUMN','column',1,'p_column','PlyMpstat.py',45),
  ('data -> INTEGER - INTEGER - INTEGER , float , float , float , float , INTEGER , float','data',17,'p_data','PlyMpstat.py',50),
  ('float -> INTEGER . INTEGER','float',3,'p_float','PlyMpstat.py',54),
]
